version: '3.9'

services:
  go-app:
    container_name: rest-api
    build: .
    environment:
      DATABASE_URL: "host=postgresql_db port=5432 user=postgres password=postgres123 dbname=dbresume sslmode=disable"
    ports:
      - "8000:8080"
    depends_on:
      - postgresql_db
  postgresql_db:
    container_name: postgresql_db
    image: postgres:14
    environment:
        POSTGRES_PASSWORD: postgres123
        POSTGRES_USER: postgres
        POSTGRES_DB: dbresume
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/load_tables.sql:/docker-entrypoint-initdb.d/load_tables.sql

volumes:  
  pgdata: {}

