version: '3.7'
services:
  postgresql_db:
    image: postgres:14
    restart: always
    volumes:
      - ./data/db/:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/load_data.sql:/docker-entrypoint-initdb.d/load_data.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB= dbresume
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= postgres123