// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/interfaces/experience_service_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/aabdullahgungor/personal-resume-api/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockIExperienceService is a mock of IExperienceService interface.
type MockIExperienceService struct {
	ctrl     *gomock.Controller
	recorder *MockIExperienceServiceMockRecorder
}

// MockIExperienceServiceMockRecorder is the mock recorder for MockIExperienceService.
type MockIExperienceServiceMockRecorder struct {
	mock *MockIExperienceService
}

// NewMockIExperienceService creates a new mock instance.
func NewMockIExperienceService(ctrl *gomock.Controller) *MockIExperienceService {
	mock := &MockIExperienceService{ctrl: ctrl}
	mock.recorder = &MockIExperienceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIExperienceService) EXPECT() *MockIExperienceServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIExperienceService) Create(experience *model.Experience) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", experience)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIExperienceServiceMockRecorder) Create(experience interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIExperienceService)(nil).Create), experience)
}

// Delete mocks base method.
func (m *MockIExperienceService) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIExperienceServiceMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIExperienceService)(nil).Delete), id)
}

// Edit mocks base method.
func (m *MockIExperienceService) Edit(experience *model.Experience) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Edit", experience)
	ret0, _ := ret[0].(error)
	return ret0
}

// Edit indicates an expected call of Edit.
func (mr *MockIExperienceServiceMockRecorder) Edit(experience interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Edit", reflect.TypeOf((*MockIExperienceService)(nil).Edit), experience)
}

// GetAll mocks base method.
func (m *MockIExperienceService) GetAll() ([]model.Experience, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]model.Experience)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIExperienceServiceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIExperienceService)(nil).GetAll))
}

// GetById mocks base method.
func (m *MockIExperienceService) GetById(id string) (model.Experience, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id)
	ret0, _ := ret[0].(model.Experience)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockIExperienceServiceMockRecorder) GetById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockIExperienceService)(nil).GetById), id)
}
